### ISSUE TITLE
validate that user who creates a worker type has the scopes they are giving to that worker type

### ISSUE THREAD

**Issue by jhford** [taskcluster/aws-provisioner#40]
We should probably make sure that whoever is updating or creating a worker type already has the scopes that the worker type is going to be given.

**Comment by petemoore** [comment]
@jhford Was this resolved in the end?

**Comment by jhford** [comment]
https://github.com/taskcluster/aws-provisioner/blob/master/src/api-v1.js#L862

We stopped allowing arbitrary scope setting in the provisioner.  Now the provisioner gets the minimum amount of scopes it needs.
